version: "3"

services:      

  server:
    image: node:16-buster
    container_name: "${PROJECT_NAME}_server"
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./reports:/usr/share/reports
    environment:
      - NODE_ENV=prod
      - NODE_PORT=3000
      - HOST=0.0.0.0
    command: npm run start
    depends_on:
      - db
    networks: 
      - appnetwork

  db:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_db"
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pqmrootpass
      MYSQL_DATABASE: pagequalitymonitor
      MYSQL_USER: pagequalitymonitor
      MYSQL_PASSWORD: qpmpass
    volumes:
      - ./mysql/:/mnt/
    ports:
      - '3306:3306'
    networks:
      - appnetwork

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    ports:
      - '8484:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pqmrootpass 
    networks:
      - appnetwork
  
networks:
  appnetwork: