version: "3"

services:      

  db:
    image: mysql:5.7
    container_name: "${PROJECT_NAME}_db"
    #restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pqmrootpass
      MYSQL_DATABASE: pagequalitymonitor
      MYSQL_USER: pagequalitymonitor
      MYSQL_PASSWORD: qpmpass
    volumes:
      - ./mysql/:/mnt/
    ports:
      - '3406:3306'
    networks:
      - appnetwork

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    #restart: always
    ports:
      - '8484:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: pqmrootpass 
    networks:
      - appnetwork
  
networks:
  appnetwork: